<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nik' => '1234567890123456',
                'id_level' => 1, 
                'nokk' => '1234567890123456',
                'nama' => 'Ahmad Muhsin',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1980-01-01',
                'alamat' => 'Jl. Merdeka No. 1',
                'agama' => 'Islam',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Karyawan',
                'pendidikan' => 'S1',
                'status_pernikahan' => 'Menikah',
            ],
            [
                'nik' => '2345678901234567',
                'id_level' => 2, 
                'nokk' => '2345678901234567',
                'nama' => 'Ahmad Duwi',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1990-02-02',
                'alamat' => 'Jl. Sudirman No. 2',
                'agama' => 'Kristen',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Wiraswasta',
                'pendidikan' => 'S2',
                'status_pernikahan' => 'Belum Menikah',
            ],
            [
                'nik' => '3456789012345678',
                'id_level' => 2, 
                'nokk' => '3456789012345678',
                'nama' => 'Ahmad Dahlan',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1975-03-03',
                'alamat' => 'Jl. Pahlawan No. 3',
                'agama' => 'Islam',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Guru',
                'pendidikan' => 'S1',
                'status_pernikahan' => 'Menikah',
            ],
            [
                'nik' => '4567890123456789',
                'id_level' => 3, 
                'nokk' => '4567890123456789',
                'nama' => 'Siti Aisyah',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1985-04-04',
                'alamat' => 'Jl. Malioboro No. 4',
                'agama' => 'Islam',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Dokter',
                'pendidikan' => 'S2',
                'status_pernikahan' => 'Menikah',
            ],
            [
                'nik' => '5678901234567890',
                'id_level' => 3, 
                'nokk' => '5678901234567890',
                'nama' => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1995-05-05',
                'alamat' => 'Jl. Pandanaran No. 5',
                'agama' => 'Hindu',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Petani',
                'pendidikan' => 'SMA',
                'status_pernikahan' => 'Belum Menikah',
            ],
            [
                'nik' => '6789012345678901',
                'id_level' => 3, 
                'nokk' => '6789012345678901',
                'nama' => 'Rudi',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1992-06-06',
                'alamat' => 'Jl. Dipayu No. 6',
                'agama' => 'Islam',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'PNS',
                'pendidikan' => 'S1',
                'status_pernikahan' => 'Menikah',
            ],
            [
                'nik' => '7890123456789012',
                'id_level' => 3, 
                'nokk' => '7890123456789012',
                'nama' => 'Anna',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1988-07-07',
                'alamat' => 'Jl. Cihampelas No. 7',
                'agama' => 'Katolik',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Guru',
                'pendidikan' => 'S2',
                'status_pernikahan' => 'Belum Menikah',
            ],
            [
                'nik' => '8901234567890123',
                'id_level' => 3, 
                'nokk' => '8901234567890123',
                'nama' => 'Siti',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1993-08-08',
                'alamat' => 'Jl. Dago No. 8',
                'agama' => 'Islam',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Pelajar',
                'pendidikan' => 'SMA',
                'status_pernikahan' => 'Belum Menikah',
            ],
            [
                'nik' => '9012345678901234',
                'id_level' => 3, 
                'nokk' => '9012345678901234',
                'nama' => 'Hadi',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1991-09-09',
                'alamat' => 'Jl. Padjajaran No. 9',
                'agama' => 'Islam',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Wiraswasta',
                'pendidikan' => 'D3',
                'status_pernikahan' => 'Belum Menikah',
            ],
            [
                'nik' => '0123456789012345',
                'id_level' => 3, 
                'nokk' => '0123456789012345',
                'nama' => 'Ani',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1996-10-10',
                'alamat' => 'Jl. Raya No. 10',
                'agama' => 'Kristen',
                'status' => 'Aktif',
                'kewarganegaraan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1',
                'status_pernikahan' => 'Belum Menikah',
            ],
        ];
        
        DB::table('m_warga')->insert($data);
    }
}
